### ISSUE TITLE
Godep not working

### ISSUE THREAD

**Issue by clanstyles** [handcraftedbits/go-bamboo-plugin#13]
I have go 1.7.4 installed.
in ~/.bashrc 
# golang setup
export GOPATH=/root/golang
export GOROOT=/root/go
export PATH=$PATH:$GOPATH/bin

/root/golang is a symlink to /root/.gvm/... and the version of go that is current.

when the build runs:
Failing task since return code of [/root/golang/bin/godep restore] was -1 while expected 0

In the bamboo data folder and project build dir the code is in there. I've tried building it by hand by running:

```
godep restore
godep: [WARNING]: godep should only be used inside a valid go package directory and
godep: [WARNING]: may not function correctly. You are probably outside of your $GOPATH.
godep: [WARNING]:	Current Directory: /home/atlassian/atlassian_data/bamboo_data/xml-data/build-dir/HEL-AD-DJ/src/myprojecthere/server
godep: [WARNING]:	$GOPATH: /root/golang

```

I don't quite understand why it's failing or how to figure out what's causing it to fail.

**Comment by clanstyles** [comment]
Fixed, permission error

**Comment by pawmart** [comment]
getting the same as root, what permissions @clanstyles if you dont mind?
