### ISSUE TITLE
Create cover output to Clover converter

### ISSUE THREAD

**Issue by handcraftedbits** [handcraftedbits/go-bamboo-plugin#4]
Create a converter that can take `go test -cover` output and convert it into Clover format.

**Comment by handcraftedbits** [comment]
Closing.  Go test results don't seem to fit well into the Clover model and supplying a `clover.xml` file isn't sufficient -- you either need a licensed Clover plugin for Bamboo or a licensed Ant/Maven plugin that generates the HTML.  Prefer the approach in #5.

**Comment by mheese** [comment]
That is not entirely true. For our Node.JS projects, we use "Istanbul" which can produce the necessary Clover output and report HTML. We also don't have a licensed Clover plugin for Bamboo, and the integration works just fine.

Not sure if that is an option, but just to let you know that there are alternatives available.

**Comment by handcraftedbits** [comment]
Thanks for the info.  Can you show me where you do this?  The problem I had was that I could generate a clover.xml no problem but it seemed like the Maven plugin was what turned it into HTML.  I had assumed Bamboo would do the conversion but it didn't appear so.

**Comment by dhulihan** [comment]
Is there an alternative coverage format that bamboo uses that we can generate a report in? How about NCover?

![screen shot 2017-08-15 at 2 56 51 pm](https://user-images.githubusercontent.com/519728/29336106-0c6b4f2c-81ca-11e7-9e9f-2335bd0dd2e2.png)

**Comment by handcraftedbits** [comment]
Ultimately I don't think Clover output fits Go code very well -- it's very much structured in terms of classes and methods.  What I think works better is what's in the issue-5 branch (which I haven't messed with in a long time unfortunately) -- merging all the go-generated HTML coverage reports together and then adding them to a custom Bamboo tab.  I already wrote code to do the merging, but what's left is:

1. Reworking the command-line/package handling in the various tasks.
2. Creating a custom Bamboo tab.

Unfortunately the Bamboo API isn't well-documented (especially when it comes to something like a custom tab -- absolutely no documentation at all) and that's kinda where I left off.

**Comment by dhulihan** [comment]
I like the idea of merging coverage reports together and a custom tab. No more transcription to awkward java reporting formats.
